version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "6789:6789"
    networks:
      - dev-net
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4567
    depends_on:
      - backend
    networks:
      - dev-net
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:17
    container_name: cinematch-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cinematch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  dev-net:

volumes:
  postgres_data: