version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - ENV=production
      - PORT=6789
      - DB_HOST=your_db_host_here
      - DB_NAME=your_db_name_here
      - DB_PORT=5432
      - DB_USER=your_db_user_here
      - DB_PASSWORD=your_db_password_here
      - JWT_SECRET=your_jwt_secret_here
      - TMDB_API_KEY=your_tmdb_api_key_here
      - AZURE_OPENAI_ENDPOINT=your_azure_openai_endpoint_here
      - AZURE_OPENAI_API_KEY=your_azure_openai_api_key_here
      - AZURE_OPENAI_DEPLOYMENT_NAME=your_azure_openai_deployment_name_here
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://flixmate.com.br/api  # caminho real da API
    environment:
      - NEXT_PUBLIC_API_URL=https://flixmate.com.br/api  # usado em tempo de execução (SSR, etc)
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network: